import { useEffect, useRef, useState } from 'react'
import { ChevronDown, ChevronUp, MonitorDot, X } from 'lucide-react'
import { pitWallTabs } from '../domain/pitWall'
import type { PitWallTabId } from '../domain/pitWall'
import { motorsportStandings } from './race'
import type { MotorsportCar, MotorsportPitRequest, MotorsportRaceConfig, MotorsportRaceState } from './types'

const clock = (value: number) => `${Math.floor(value/3600)}:${Math.floor(value/60%60).toString().padStart(2,'0')}:${Math.floor(value%60).toString().padStart(2,'0')}`
const lapTime = (value: number | null) => value === null ? '—' : `${Math.floor(value/60)}:${(value%60).toFixed(3).padStart(6,'0')}`
export function MotorsportPitWallPanel({config,state,selectedId,onSelect,onClose,onPit,onPace}: {
  config: MotorsportRaceConfig; state: MotorsportRaceState; selectedId:string
  onSelect:(id:string)=>void; onClose:()=>void; onPit:(request:MotorsportPitRequest)=>void
  onPace:(id:string,mode:NonNullable<MotorsportCar['paceMode']>)=>void
}) {
  const [tab,setTab] = useState<PitWallTabId>('overview')
  const [driverChange,setDriverChange] = useState<{entryId:string;index:number}|null>(null)
  const [fuel,setFuel] = useState(1), [tyres,setTyres] = useState(true)
  const close = useRef<HTMLButtonElement>(null)
  const closeAction = useRef(onClose); closeAction.current = onClose
  const standings = motorsportStandings(state,config), index = standings.findIndex(row=>row.entry.id===selectedId)
  const {entry,car,classPosition} = standings[Math.max(0,index)]
  // A map selection also changes the car. Never carry the previous car's
  // replacement-driver index into a different crew.
  const nextDriver = driverChange?.entryId === entry.id ? driverChange.index : null
  useEffect(()=>{close.current?.focus(); const handler=(event:KeyboardEvent)=>{if(event.key==='Escape')closeAction.current()};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler)},[])
  const select = (id:string) => {setDriverChange(null);onSelect(id)}
  const lapsLeft = config.format.kind === 'laps' ? Math.max(0,config.format.laps-car.laps) : null
  const fuelLaps = car.fuelKg / (entry.machine.fuelKgPerKm.value*config.course.lengthM/1000)
  return <section className="hud pit-wall-panel motorsport-pit-wall" aria-label="pit wall" role="dialog">
    <header className="pit-wall-header"><span className="pit-wall-title"><MonitorDot size={14}/>PIT WALL</span><span className="pit-wall-identity" style={{borderColor:entry.color}}>#{entry.number} {entry.drivers[car.driverIndex].name}</span><span className="pit-wall-car-select" aria-label="Select car" role="group"><button aria-label="Previous pit wall car" disabled={index<=0} onClick={()=>select(standings[index-1].entry.id)}><ChevronUp size={13}/></button><button aria-label="Next pit wall car" disabled={index>=standings.length-1} onClick={()=>select(standings[index+1].entry.id)}><ChevronDown size={13}/></button></span><span className="pit-wall-standing"><strong>{entry.classId.toUpperCase()} P{classPosition}</strong><span>LAP {car.laps+1} / SIM</span></span><button aria-label="Close pit wall" ref={close} onClick={onClose}><X size={14}/></button></header>
    <div className="pit-wall-tabs" aria-label="Pit wall sections" role="tablist">{pitWallTabs.map(item=><button role="tab" key={item.id} aria-selected={tab===item.id} aria-controls="motorsport-pit-tab" id={`motorsport-pit-${item.id}`} onClick={()=>setTab(item.id)}>{item.label}</button>)}</div>
    <div className="pit-wall-body" id="motorsport-pit-tab" role="tabpanel" aria-labelledby={`motorsport-pit-${tab}`}>
      <label>Selected car<select aria-label="Selected engineering car" value={entry.id} onChange={event=>select(event.target.value)}>{standings.map(row=><option key={row.entry.id} value={row.entry.id}>#{row.entry.number} {row.entry.drivers[row.car.driverIndex].name}</option>)}</select></label>
      {tab==='overview'&&<><h3>{entry.team}</h3><p>{entry.machine.name}</p><div className="insight-grid"><span>Last / best</span><strong>{lapTime(car.lastLapSeconds)} / {lapTime(car.bestLapSeconds)}</strong><span>Speed / gear</span><strong>{Math.round(car.speedMps*3.6)} km/h / {car.gear}</strong><span>Fuel / range (SIM)</span><strong>{car.fuelKg.toFixed(1)} kg / {fuelLaps.toFixed(1)} laps</strong><span>Tyres / life</span><strong>{car.tyreSets.at(-1)?.compound} / {Math.round(car.tyreLife*100)}%</strong><span>Current stint</span><strong>{clock(car.stintSeconds)}</strong><span>Pit stops / status</span><strong>{car.pits} / {car.status}</strong><span>Driver ability</span><strong>{entry.drivers[car.driverIndex].overall ?? '—'}</strong></div><p>能力出典：{entry.drivers[car.driverIndex].ratingSource ?? '未収録・中立SIM値'}</p></>}
      {tab==='lap-log'&&<div className="pit-wall-lap-log"><h3>Lap log · measured crossings</h3><div className="motorsport-table-scroll"><table><thead><tr><th>Lap</th><th>Time</th><th>Driver</th><th>Tyres</th><th>Type</th></tr></thead><tbody>{[...(car.lapHistory??[])].reverse().map(lap=><tr key={lap.lap}><td>{lap.lap}</td><td>{lapTime(lap.seconds)}</td><td>{entry.drivers[lap.driverIndex]?.name}</td><td>{lap.compound}</td><td>{lap.pit?'OUT / PIT':'TIMED'}</td></tr>)}</tbody></table></div></div>}
      {tab==='strategy'&&<><h3>Next stop</h3><p>Fuel range {fuelLaps.toFixed(1)} laps · {lapsLeft===null?'Timed race':`${lapsLeft} laps remaining`}</p><label>Driver change<select aria-label="Motorsport next driver" value={nextDriver??''} disabled={entry.drivers.length===1} onChange={event=>setDriverChange(event.target.value===''?null:{entryId:entry.id,index:Number(event.target.value)})}><option value="">No change</option>{entry.drivers.map((driver,index)=><option key={driver.id} value={index}>{driver.name}</option>)}</select></label><label>Fuel target<input aria-label="Motorsport refuel target" type="range" min="0" max="1" step="0.05" value={fuel} disabled={config.championship==='kyojo' && config.applicationMode!=='free'} onChange={event=>setFuel(Number(event.target.value))}/>{Math.round(fuel*100)}%</label><label><input type="checkbox" checked={tyres} onChange={event=>setTyres(event.target.checked)}/>Change tyres</label><h3>Crew / driving time</h3>{entry.drivers.map((driver,index)=><p key={driver.id}>{driver.name} · {clock(car.driverSeconds[index])}</p>)}<p>自動戦略は燃料・タイヤ・仮想エネルギーを監視します。WECの給油とタイヤは順次作業、INDYCARは並行作業です。</p><p>{car.pitRequest?'PIT REQUESTED':'No pending pit request'}</p></>}
      {tab==='systems'&&<><h3>Car systems · SIM</h3><div className="insight-grid"><span>{entry.classId==='indycar'?'Hybrid supercapacitor':'Hybrid store'}</span><strong>{entry.machine.hybridCapacityMj.value>0?`${car.hybridEnergyMj.toFixed(3)} / ${entry.machine.hybridCapacityMj.value.toFixed(3)} MJ`:'NOT FITTED'}</strong><span>Deploy / recover</span><strong>{(car.hybridPowerKw??0).toFixed(1)} / {(car.regenerationPowerKw??0).toFixed(1)} kW</strong><span>Recovered total</span><strong>{(car.hybridRecoveredMj??0).toFixed(3)} MJ</strong><span>Power limit</span><strong>{entry.machine.hybridPowerKw.value} kW · {entry.machine.hybridPowerKw.basis}</strong><span>Hybrid deployment</span><strong>{car.hybridDeployedMj.toFixed(3)} MJ</strong><span>Virtual energy</span><strong>{car.virtualEnergyMj?.toFixed(1)??'N/A'} MJ</strong><span>Push to pass</span><strong>{entry.classId==='indycar'?`${car.pushToPassSeconds.toFixed(1)} s`:'N/A'}</strong><span>Tyre temperature</span><strong>{car.tyreTemperatureC.toFixed(1)}°C</strong><span>Penalty</span><strong>{car.penaltySeconds.toFixed(1)} s</strong></div><h3>Tyre sets</h3>{car.tyreSets.map((set,index)=><p key={index}>{index+1}: {set.compound} · {set.completedLaps} laps</p>)}</>}
      {tab==='weather'&&<><h3>Weather & track</h3><div className="insight-grid"><span>Surface (SIM)</span><strong>{config.weather.toUpperCase()}</strong><span>Length</span><strong>{(config.course.lengthM/1000).toFixed(3)} km</strong><span>Course</span><strong>{config.course.kind}</strong><span>Pit limit (SIM)</span><strong>{config.course.pitSpeedKph.value} km/h</strong><span>Air / track temperature</span><strong>UNAVAILABLE</strong></div><p>{config.course.geometryBasis}</p></>}
      {tab==='race-control'&&<><h3>{state.flag.toUpperCase()} · Race control</h3>{car.warnings.map((warning,index)=><p key={`warning:${index}`}>{warning}</p>)}{state.events.filter(event=>event.entryId===null||event.entryId===entry.id).slice(-50).reverse().map((event,index)=><p key={index}>{clock(event.seconds)} · {event.message}</p>)}</>}
    </div>
    <footer className="pit-wall-commands"><div aria-label="Pit stop instruction" role="group"><button className="pit-wall-box-command" disabled={state.phase!=='racing'||car.status!=='running'} onClick={()=>onPit({entryId:entry.id,fuelFraction:config.championship==='kyojo' && config.applicationMode!=='free'?0:fuel,changeTyres:tyres,nextDriverIndex:nextDriver})}>BOX / ピットを指示</button></div><div aria-label="Driver pace instruction" role="group">{(['push','standard','save','defend'] as const).map(mode=><button className="pit-wall-pace-command" key={mode} aria-pressed={(car.paceMode??'standard')===mode} disabled={state.phase==='finished'} title="SIM pace instruction" onClick={()=>onPace(entry.id,mode)}>{mode==='standard'?'STD':mode.toUpperCase()}</button>)}</div></footer>
  </section>
}
